// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDSAsinQrla7XC3J730zwOScHuOl1gNw4',
    appId: '1:33179150728:web:2da521a66a967b6fa7f23d',
    messagingSenderId: '33179150728',
    projectId: 'connectcall-12653',
    authDomain: 'connectcall-12653.firebaseapp.com',
    storageBucket: 'connectcall-12653.firebasestorage.app',
    measurementId: 'G-VS8XEKN7TN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1sFdBvBYPubq0A4WKSV960fCwsHSMK84',
    appId: '1:33179150728:ios:b2e5531c3350a7b4a7f23d',
    messagingSenderId: '33179150728',
    projectId: 'connectcall-12653',
    storageBucket: 'connectcall-12653.firebasestorage.app',
    iosBundleId: 'com.example.connectCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDSAsinQrla7XC3J730zwOScHuOl1gNw4',
    appId: '1:33179150728:web:46ae4147a21eae07a7f23d',
    messagingSenderId: '33179150728',
    projectId: 'connectcall-12653',
    authDomain: 'connectcall-12653.firebaseapp.com',
    storageBucket: 'connectcall-12653.firebasestorage.app',
    measurementId: 'G-VVS40QF9CD',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1sFdBvBYPubq0A4WKSV960fCwsHSMK84',
    appId: '1:33179150728:ios:b2e5531c3350a7b4a7f23d',
    messagingSenderId: '33179150728',
    projectId: 'connectcall-12653',
    storageBucket: 'connectcall-12653.firebasestorage.app',
    iosBundleId: 'com.example.connectCall',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5PNpxSiJ4xpx9ChmRbgiYLKgDYghD66g',
    appId: '1:33179150728:android:0d6d70c151a0e4dea7f23d',
    messagingSenderId: '33179150728',
    projectId: 'connectcall-12653',
    storageBucket: 'connectcall-12653.firebasestorage.app',
  );
}
